import static org.junit.Assert.*;

import org.junit.Test;

public class AssignmentTest {

	/*
	 * getDuration -- autogenerated, no test
	 */
	
	/*
	 * getBeginNode -- autogenerated, no test
	 */
	
	/*
	 * getEndNOde -- autogenerated, no test
	 */

}
