import static org.junit.Assert.*;

import java.util.ArrayList;
import java.util.List;

import org.junit.Test;

public class DependencyTest {
	/*
	 * Testing the addDependencyEdge method in the enum
	 */
	@Test
	public void test_begin_begin() {
		Assignment fromAssignment = new Assignment(4);
		Assignment toAssignment = new Assignment(5);	
		Dependency testDependency = new Dependency(fromAssignment, Dependency.DependencyType.BEGINBEGIN, toAssignment);

		
		testDependency.dependencyType.addDependencyEdge(testDependency);
		
		assertEquals(fromAssignment.begin.getOutgoingEdges().get(0), toAssignment.begin.getIncomingEdges().get(0));
	}
	
	@Test
	public void test_begin_end() {
		Assignment fromAssignment = new Assignment(4);
		Assignment toAssignment = new Assignment(5);	
		Dependency testDependency = new Dependency(fromAssignment, Dependency.DependencyType.BEGINEND, toAssignment);

		
		testDependency.dependencyType.addDependencyEdge(testDependency);
		
		assertEquals(fromAssignment.begin.getOutgoingEdges().get(0), toAssignment.end.getIncomingEdges().get(0));
	}
	
	@Test
	public void test_end_begin() {
		Assignment fromAssignment = new Assignment(4);
		Assignment toAssignment = new Assignment(5);	
		Dependency testDependency = new Dependency(fromAssignment, Dependency.DependencyType.ENDBEGIN, toAssignment);

		
		testDependency.dependencyType.addDependencyEdge(testDependency);
		
		assertEquals(fromAssignment.end.getOutgoingEdges().get(0), toAssignment.begin.getIncomingEdges().get(0));
	}
	
	@Test
	public void test_end_end() {
		Assignment fromAssignment = new Assignment(4);
		Assignment toAssignment = new Assignment(5);	
		Dependency testDependency = new Dependency(fromAssignment, Dependency.DependencyType.ENDEND, toAssignment);

		
		testDependency.dependencyType.addDependencyEdge(testDependency);
		
		assertEquals(fromAssignment.end.getOutgoingEdges().get(0), toAssignment.end.getIncomingEdges().get(0));
	}
	
	/*
	 * getDependencyType -- no need to test because it's autogenerated!
	 */
	
	

}